#!/bin/bash

# USAGE: ssh www.jaylen.com.ar "~/bin/whitelist-ip-4-squid-srv ROSALES $(public-ip)"

SQUID_CONFIG=/etc/squid/squid.conf
PROXY_PORT-3128
LABEL="$1"
NEW_IP="$2"

# find out the previous IP associated with LABEL
IP_RE='[0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}'
OLD_IP=$(egrep "acl $LABEL src ($IP_RE)" $SQUID_CONFIG | cut -d ' ' -f 4)
echo "Changing old IP: $OLD_IP => new IP: ${NEW_IP} for label '${LABEL}'"

# substitute OLD_IP for NEW_IP
sudo sed -i -E -e "s/(acl $LABEL src) $IP_RE/\1 $NEW_IP/" $SQUID_CONFIG
sudo systemctl reload squid
UFW_RULE_NBR=$(sudo ufw status numbered | egrep "$PROXY_PORT/tcp\s+ALLOW IN\s+$OLD_IP" | sed -E 's/^\[([0-9]+)\]/\1/' | cut -d ' ' -f 1)
# echo "UFW RULE NBR: $UFW_RULE_NBR"
sudo ufw allow proto tcp from $NEW_IP to any port $PROXY_PORT
yes | sudo ufw delete $UFW_RULE_NBR
