#!/bin/bash

# USAGE: ssh www.jaylen.com.ar "~/bin/whitelist-ip-4-openvpn-srv ROSALES $(public-ip)"

SQUID_CONFIG=/etc/squid/squid.conf
OPENVPN_PORT=1194
LABEL="$1"
NEW_IP="$2"

# echo "LABEL: $LABEL, NEW IP: $NEW_IP"
# find out the previous IP associated with LABEL
IP_RE='[0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}'
OLD_IP=$(egrep "acl $LABEL src ($IP_RE)" $SQUID_CONFIG | cut -d ' ' -f 4)
echo "Changing old IP: $OLD_IP => new IP: ${NEW_IP} for label '${LABEL}'"

UFW_RULE_NBR=$(sudo ufw status numbered | egrep "$OPENVPN_PORT/udp\s+ALLOW IN\s+$OLD_IP" | sed -E 's/^\[([0-9]+)\]/\1/' | cut -d ' ' -f 1)
# echo "UFW RULE NBR: $UFW_RULE_NBR"
sudo ufw allow proto udp from $NEW_IP to any port $OPENVPN_PORT
yes | sudo ufw delete $UFW_RULE_NBR
